CS_project/Controllers/DatasetsController.cs
using CS_project.Models;
using ExcelDataReader;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CS_project.Controllers
{
    [Authorize]
    public class DatasetsController : Controller
    {
        [HttpGet]
        public IActionResult Index(List<Dataset> datasets = null)
        {
            datasets = datasets == null ? new List<Dataset>() : datasets;
            return View(datasets);
        }
        [HttpPost]
        [Obsolete]
        public IActionResult Index(IFormFile file,[FromServices] IHostingEnvironment hostingEnvironment)
        {
            string filename = $"{hostingEnvironment.WebRootPath}\\files\\{file.FileName}";
            using (FileStream filestream = System.IO.File.Create(filename))
            {
                file.CopyTo(filestream);
                filestream.Flush();
            }

            var datasets = this.GetDatasetList(file.FileName);
            return Index(datasets);
        }

        private List<Dataset> GetDatasetList(string fName)
        {
            List<Dataset> datasets = new List<Dataset>();
            var fileName = $"{Directory.GetCurrentDirectory()}{@"\wwwroot\files"}" + "\\" + fName;
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
            using (var stream = System.IO.File.Open(fileName, FileMode.Open, FileAccess.Read))
            {
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    while(reader.Read())
                    {
                        datasets.Add(new Dataset()
                        {
                            Name = reader.GetValue(0).ToString(),
                            Email = reader.GetValue(1).ToString(),
                            Amount = reader.GetValue(2).ToString(),
                            PhoneNo = reader.GetValue(3).ToString(),
                            Location = reader.GetValue(4).ToString()
                        }); 
                    }
                }
            }
            return datasets;
        }
    }
}

CS_project/Controllers/TestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CS_project.Models;
using System.Security.Claims;
using CS_project.Data;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using CS_project.Areas.Identity.Data;

namespace CS_project.Controllers
{
    [Authorize]
    public class TestController : Controller
    {
        private readonly string wwwrootDirectory = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
        public string str;
        public IActionResult Index()
        {
            List<string> content = Directory.GetFiles(wwwrootDirectory, "*.pbix").Select(Path.GetFileName).ToList();

            return View(content);
        }
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            var UserName = HttpContext.User.Identity.Name;
            str = UserName;
            return Ok(UserName);
        }
        [HttpPost]
        public async Task<IActionResult> Index(IFormFile myFile)
        {
            var userName = User.FindFirstValue(ClaimTypes.Name);
            //var context = new CS_project_authContext();
            //var username = User.Identity.Name;

            //if (!string.IsNullOrEmpty(username))
            //{
            //    var user = context.Users.SingleOrDefault(u => u.UserName == username);
            //    string fullName = string.Concat(new string[] { user.firstName, " ", user.lastName });
            //}
                //var userName = User.FindFirst("firstName").Value;
                /*var userName = User.FindFirstValue(ClaimTypes.NameIdentifier);*///gives userid
                                                                                  // var userName = User.FindFirstValue(ClaimTypes.GivenName);
                if (myFile != null)
            {
                //preparing the path
                //var user = User.Identity.GetUserId();
                //System.Security.Claims.ClaimsPrincipal currentUser = this.User;
                //bool isAdmin = currentUser.IsInRole("Admin");
                //var id = _userManager.GetUserId(User);
                var ext = Path.GetExtension(myFile.FileName);
                if (ext.Equals(".pbix"))
                {
                    var path = Path.Combine(wwwrootDirectory, DateTime.Now.ToString("dd - MM - yyyy") + "____" + myFile.FileName + "____" + userName + "____"+DateTime.Now.Ticks.ToString()+Path.GetExtension(myFile.FileName));

                    //saving the file
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await myFile.CopyToAsync(stream);
                    }

                    //return RedirectToAction("Index");
                }
                //else
                //{
                //    TempData["Message"] = "This is my Error";
                //}
                return RedirectToAction("Index");
            }

            ViewData["error"] = "this is my error";
            return RedirectToAction("Index");
            //return View();
        }

        public async Task<IActionResult> DownloadFile(string filePath)
        {
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", filePath);

            var memory = new MemoryStream();

            using (var stream = new FileStream(path,FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }

            memory.Position = 0;
            var contentType = "APPLICATION/octet-stream";
            var fileName = Path.GetFileName(path);

            return File(memory,contentType,fileName);

        }

    }
}

CS_project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Deloitte7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        body {
            /* background-image: url(https://igaming.org/wp-content/uploads/2021/08/deloitte-crypto-1024x576.jpg);*/
            /*background-image: url("~/wwwroot/css/assets/deloitte-crypto-new-1024x576.jpg");*/
            background: #000 center url(https://i.ibb.co/zFFgcym/deloitte-crypto-new-1024x576.jpg) no-repeat;
            /*  filter: blur(8px);
           -webkit-filter: blur(8px);*/
        }
    </style>
</head>
<body>
    @*<img src="~/css/assets/deloitte-crypto-new-1024x576.jpg" />*@
    <header style="background-color: #183a7a">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a style="color:black;background-color:white" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <a style="color: black;background-color: white" class="navbar-brand" asp-area="" asp-controller="Test" asp-action="Index">Upload</a>
                <a style="color: black;background-color: white" class="navbar-brand" asp-area="" asp-controller="Datasets" asp-action="Index">Dataset</a>
                @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">*@
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_Loginpartial.cshtml" />
                </div>
                <img style="width:10%;height:20%;display:block;margin-left:100px;margin-right:auto" src="~/css/assets/Deloitte_logo_black.png"
                     class="collapse d-sm-inline-flex flex-sm-row-reverse">
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color:#3a4a4b" class="border-top footer text-muted">
        <div style="color:white"class="container">
            &copy;Copyright &commat;Deloitte.com | 2021 <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>